name: J1 Integration deployment

on:
  release:
    types:
      - published

jobs:
  j1-integration-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Get integration name
        id: get-integration-name
        uses: actions/github-script@0.9.0
        with:
          script: |
            const repositoryName = context.payload.repository.name
            const integrationName = repositoryName.replace("graph-", "")
            core.setOutput('integrationName', integrationName)
      - name: Get version number
        id: get-version-number
        uses: actions/github-script@0.9.0
        with:
          script: |
            const tagName = context.payload.release.tag_name
            const versionNumber = tagName.replace("v", "")
            core.setOutput('versionNumber', versionNumber)
      - name: Bump integration deployment version
        uses: JupiterOne/integration-github-actions/create-integration-deployment@v1
        with:
          integrationName: $
          releaseNotes: $
          version: $
          githubToken: $
          npmAuthToken: $
